import "../styles/globals.css";

import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { ReduxProvider } from "@/components";

const nunito = Nunito({
    subsets: ["latin"],
    weight: ["400", "700"],
    variable: "--font-nunito",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body suppressHydrationWarning className={`${nunito.variable} antialiased`}>
                <ReduxProvider>
                    { children }
                </ReduxProvider>
            </body>
        </html>
    );
}
